# Generated by Django 4.0.1 on 2022-12-27 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='tg_username',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Имя пользователя'),
        ),
    ]
