# Generated by Django 4.0.1 on 2022-12-31 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_tguser_tg_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'Telegram пользователь', 'verbose_name_plural': 'Telegram пользователи'},
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='tg_username',
        ),
    ]
