# Generated by Django 4.0.1 on 2022-12-15 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_tguser_chat_id_alter_tguser_user_ud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='chat_id',
            field=models.BigIntegerField(verbose_name='id чата'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='user_ud',
            field=models.BigIntegerField(verbose_name='id пользователя'),
        ),
    ]
