# Generated by Django 4.0.1 on 2022-12-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_tguser_username_alter_tguser_tg_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='TG USERNAME'),
        ),
    ]
