# Generated by Django 4.0.1 on 2022-12-27 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0005_alter_tguser_options_alter_tguser_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'TG пользователь', 'verbose_name_plural': 'TG пользователи'},
        ),
        migrations.RemoveField(
            model_name='tguser',
            name='username',
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tg_chat_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tg_user_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
